name: ğŸ­ Playwright Screen Reader

on:
  workflow_call:

permissions:
  actions: write
  contents: write

jobs:
  playwright-screen-reader:
    name: ğŸ§ªğŸ­ - screen-reader - ${{ matrix.os }} - ${{ matrix.framework }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        framework: [react]
    steps:
      - name: â¬ Checkout repo
        uses: actions/checkout@v4

      - name: ğŸ”„ Init Cache Default
        uses: ./.github/actions/npm-cache

      - name: ğŸ¦® Guidepup Setup
        uses: guidepup/setup-action@0.15.3
        with:
          record: true

      - name: ğŸ†™ Set env for os
        shell: bash
        env:
          OS: ${{ matrix.os }}
        run: |
          if [[ $OS == "windows-latest" ]]; then
            echo "PATH=C:\Users\runneradmin\AppData\Local\ms-playwright" >> "$GITHUB_ENV"
            echo "BROWSER=chromium" >> "$GITHUB_ENV"
          else
            echo "PATH=~/Library/Caches/ms-playwright" >> "$GITHUB_ENV"
            echo "BROWSER=webkit" >> "$GITHUB_ENV"
          fi

      - uses: actions/cache@v4
        id: playwright-cache
        with:
          path: "~/.cache/ms-playwright"
          key: "${{ runner.os }}-playwright-1.43.1"
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright's dependencies
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: |
          npx playwright install --with-deps ${{ env.BROWSER }}
          echo "-------------------"
          ls ${{ env.PATH }}

      - name: ğŸ‘©â€ğŸ”¬ Test showcase with Playwright ğŸ­
        working-directory: screen-reader-test
        env:
          HOME: /root
        run: |
          npm run test:screen-reader:${{ matrix.os }}

      - name: ğŸ†™ Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.framework }}-screen-reader-${{ matrix.os }}
          path: ./screen-reader-test/${{ matrix.framework }}-showcase/test-results
          retention-days: 30
